---
controller_templates:
  - name: Get Stats JT
    job_type: run
    inventory: Controllers
    project: Get Controller Stats
    playbook: getControllerStats.yml
    ask_variables_on_launch: true
    extra_vars:
      controller_hostname:
      controller_password:
...
