---
controller_templates:
  - name: Get Stats JT
    credentials:
      - aap_admin
    job_type: run
    inventory: Localhost_inventory
    project: Get Controller Stats
    playbook: getControllerStats.yml
    ask_variables_on_launch: true
    extra_vars:
      controller_hostname:
      controller_password:

  - name: Controller as Code JT
    credentials:
      - aap_admin
    job_type: run
    inventory: Controllers
    project: Ansible Controller as Code
    playbook: controller_config.yml
    webhook_service: 'github'
    webhook_credential: CaC_seed_pat
...
