---
controller_templates:
  - name: Get Stats JT
    credentials:
      - aap_admin
    job_type: run
    inventory: dev_inventory
    project: Get Controller Stats Dev
    playbook: getControllerStats.yml
    ask_variables_on_launch: true
    extra_vars:
      controller_hostname:
      controller_password:
  - name: Install RHEL Packages
    credentials:
      - Workshop Credential
    job_type: run
    inventory: Workshop Inventory
    project: Ansible Plays for Dev
    playbook: ansiblePackages.yaml
  - name: Dynamic Inventory
    credentials:
      - Workshop Credential
    job_type: run
    inventory: Workshop Inventory
    project: Ansible Plays for Dev
    playbook: dynamicInventory.yml
  
...
