---
controller_templates:
  - name: Get Stats JT
    credentials:
      - aap_admin
      - Master Creds
    job_type: run
    inventory: Localhost_inventory
    project: Get Controller Stats
    playbook: getControllerStats.yml
    ask_variables_on_launch: true
    extra_vars:
      controller_hostname:
      controller_password:
...
