---
controller_roles:
  - user: spec_user
    users:
      - dev_user1
      - dev_user2
    target_teams: "DevOps"
    role: member
  - team: "DevOps"
    organization: Dev
    roles:
      - execute
      - read
  - user: spec_user
    users:
      - net_user1
      - net_user2
    target_teams: "NetOps"
    role: member
  - team: "NetOps"
    organization: Dev
    roles:
      - execute
      - read
  - user: spec_user
    users:
      - sys_user1
      - sys_user2
    target_teams: "SysOps"
    role: member
  - team: "SysOps"
    organization: Dev
    roles:
      - execute
      - read
...
